public with sharing class VFGuestController {

    public PageReference SaveGuest() {
        return null;
    }


    public String guestName { get; set; }

    public String guestList { get; set; }

    public String selectedGuest { get; set; }

    public PageReference searchGuest() {
        return null;
    }


    public String eventList { get; set; }

    public String selectedEvent { get; set; }

    public PageReference SearchEvent() {
        return null;
    }


    public String endDate { get; set; }

    public String startDate { get; set; }
}